server:
  port: 9001

spring:
  application:
    name: springboot02_jpa
  datasource:
    url: jdbc:mysql://localhost:3306/springbootjpa?useUnicode=true&characterEncoding=utf-8&useSSL=true
    data-username: root
    data-password: peng1365451772
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 新增数据库链接必须的参数
    # 控制台显示SQL
    show-sql: true
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: ''


